[modules]
autoload=yes
load => res_http_websocket.so
load => res_websocket_client.so
load => res_pjsip.so
load => res_pjsip_authenticator_digest.so
load => res_pjsip_endpoint_identifier_user.so
load => res_pjsip_registrar.so
load => res_pjsip_transport_websocket.so
load => res_crypto.so
load => res_srtp.so
load => chan_pjsip.so
load => chan_websocket.so
load => app_dial.so
load => app_playback.so
load => codec_alaw.so
load => codec_ulaw.so
load => codec_resample.so
